### ISSUE TITLE
Scheunen Model von innen üerbarbeiten

### ISSUE THREAD

**Issue by BenediktBeuttler** [p-schulz/codevember2016#9]
Aktuell kann man von innen nach außen schauen.
VORSCHLAG: Man dis-attached die kamera vom schaf wenn es durch das tor ist. dann muss man das model nicht überarbeiten

**Comment by schlenger** [comment]
die kamera schaut grade eh nur nach vorne. aber fixen sollen wir das so oder so. is ja nur double sided für die plane @p-schulz

**Comment by p-schulz** [comment]
habs Model gefixed
